version: "3.7"
services:
    streaming:
        build:
            dockerfile: atalaia-streaming/Dockerfile
            context: .
            target: final
        image: atalaia-streaming
        container_name: atalaia-streaming
        # deploy:
        #     restart_policy:
        #         condition: on-failure
        #         delay: 5s
        #         max_attempts: 5
        #         window: 120s
        restart: on-failure
        env_file: ~/atalaia.env
        volumes:
            - "~/Videos/atalaia:/data/local"
